#!/usr/bin/env bash
#
# One command that keeps the three copies of this project from drifting:
#
#   1. feature/android-port on Hakim3691/binance-triangle-arbitrage   (source of truth)
#   2. Hakim3691/binance-triangle-arbitrage-android                  (standalone mirror)
#   3. the offline package and its APK                                (what gets installed)
#
# Run it after every change to the Android code. It refuses to run on a dirty
# tree, so what lands in the mirror is exactly what is committed, and it always
# rebuilds and republishes the APK - the binary is a build output, not something
# to be remembered.
#
# Usage:  tools/sync-and-build.sh [--no-mirror] [--skip-tests]
#
set -euo pipefail

# Resolve paths from this script's location so it works from any cwd.
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$HERE/.." && pwd)"        # .../android
WORKSPACE_DIR="$(cd "$PROJECT_DIR/.." && pwd)" # repo root that contains android/
# Sibling checkouts of the same project, discovered next to the workspace when
# possible so the script works regardless of which user runs it. Both can be
# overridden with BTA_MIRROR_DIR / BTA_PACKAGE_DIR.
_default_sibling() {
  local name="$1"
  local candidate
  for candidate in "$WORKSPACE_DIR/../$name" "$HOME/$name" "/home/daytona/$name"; do
    if [ -d "$candidate" ]; then printf '%s' "$candidate"; return; fi
  done
  printf '%s' "$HOME/$name"
}
MIRROR_DIR="${BTA_MIRROR_DIR:-$(_default_sibling binance-triangle-arbitrage-android)}"
PACKAGE_DIR="${BTA_PACKAGE_DIR:-$(_default_sibling bta-android-offline-package)}"

DO_MIRROR=1
RUN_TESTS=1
for arg in "$@"; do
  case "$arg" in
    --no-mirror)  DO_MIRROR=0 ;;
    --skip-tests) RUN_TESTS=0 ;;
    -h|--help)    sed -n '2,20p' "$0"; exit 0 ;;
    *) echo "unknown option: $arg" >&2; exit 2 ;;
  esac
done

# The Android SDK can arrive either way; Gradle needs one of them.
export ANDROID_HOME="${ANDROID_HOME:-${ANDROID_SDK_ROOT:-/opt/android-sdk}}"
if [ ! -d "$ANDROID_HOME" ]; then
  echo "Android SDK not found at $ANDROID_HOME - set ANDROID_HOME." >&2
  exit 1
fi

cd "$WORKSPACE_DIR"

BRANCH="$(git rev-parse --abbrev-ref HEAD)"
COMMIT="$(git rev-parse --short HEAD)"
dirty="$(git status --porcelain -- android | grep -v '^?? android/\(build\|app/build\)/' || true)"
if [ -n "$dirty" ]; then
  echo "android/ has uncommitted changes:" >&2
  echo "$dirty" >&2
  echo "" >&2
  echo "Commit them first, so the mirror and the APK match the branch." >&2
  exit 1
fi

echo "==> source of truth: $BRANCH @ $COMMIT ($PROJECT_DIR)"

# ---------------------------------------------------------------- mirror
if [ "$DO_MIRROR" -eq 1 ]; then
  if [ -d "$MIRROR_DIR/.git" ]; then
    if [ -n "$(git -C "$MIRROR_DIR" status --porcelain)" ]; then
      echo "!! $MIRROR_DIR has uncommitted changes - refusing to overwrite." >&2
      echo "   Commit or stash them there first." >&2
      exit 1
    fi
    echo "==> syncing mirror: $MIRROR_DIR"
    # Copy tracked files only, so generated output never reaches the mirror and
    # deletions on the branch propagate instead of lingering.
    (cd "$PROJECT_DIR" && git ls-files -z . | tar --null -cf - -T -) \
      | (cd "$MIRROR_DIR" && tar -xf -)

    # Remove files the branch no longer tracks.
    (cd "$PROJECT_DIR" && git ls-files . ) > /tmp/.bta-tracked.$$
    (cd "$MIRROR_DIR" && find . -type f \
        -not -path './.git/*' -not -path './build/*' -not -path './app/build/*' \
        -not -path './.gradle/*' -not -path './.kotlin/*') \
      | sed 's|^\./||' | sort > /tmp/.bta-present.$$
    comm -13 <(sort /tmp/.bta-tracked.$$) /tmp/.bta-present.$$ \
      | while read -r f; do rm -f "$MIRROR_DIR/$f"; done
    rm -f /tmp/.bta-tracked.$$ /tmp/.bta-present.$$

    if [ -n "$(git -C "$MIRROR_DIR" status --porcelain)" ]; then
      git -C "$MIRROR_DIR" add -A
      git -C "$MIRROR_DIR" commit -q \
        -m "Sync from binance-triangle-arbitrage@$BRANCH ($COMMIT)

The Android port lives on the $BRANCH branch of the Node.js repository
until its own repository is available. This mirror is regenerated by
android/tools/sync-and-build.sh, so do not edit it by hand."
      echo "    mirror committed: $(git -C "$MIRROR_DIR" rev-parse --short HEAD)"
    else
      echo "    mirror already up to date"
    fi
  else
    echo "!! no git repo at $MIRROR_DIR - skipping mirror." >&2
    echo "   Set BTA_MIRROR_DIR to point at it." >&2
  fi
fi

# ---------------------------------------------------------------- tests
if [ "$RUN_TESTS" -eq 1 ]; then
  echo "==> unit tests"
  (cd "$PROJECT_DIR" && ./gradlew testDebugUnitTest --no-daemon -q)
fi

# ---------------------------------------------------------------- build
echo "==> assembling debug APK"
(cd "$PROJECT_DIR" && ./gradlew assembleDebug --no-daemon -q)

APK="$PROJECT_DIR/app/build/outputs/apk/debug/app-debug.apk"
[ -f "$APK" ] || { echo "!! no APK produced" >&2; exit 1; }

# Read identity from the built artifact rather than trusting the build script.
AAPT="$(ls -d "$ANDROID_HOME"/build-tools/*/aapt2 2>/dev/null | sort -V | tail -1 || true)"
IDENTITY=""
if [ -n "$AAPT" ]; then
  IDENTITY="$("$AAPT" dump badging "$APK" 2>/dev/null | grep -m1 '^package:' || true)"
fi
MD5="$(md5sum "$APK" | cut -d' ' -f1)"
SIZE="$(stat -c%s "$APK")"

echo "==> APK $SIZE bytes"
echo "    md5    $MD5"
echo "    $IDENTITY"

# ---------------------------------------------------------------- publish
if [ -d "$PACKAGE_DIR" ]; then
  echo "==> refreshing offline package: $PACKAGE_DIR"
  cp "$APK" "$PACKAGE_DIR/app-debug.apk"
  (cd "$PROJECT_DIR" && zip -qr "$PACKAGE_DIR/binance-triangle-arbitrage-android-src.zip" . \
      -x 'build/*' '.gradle/*' '.kotlin/*' 'local.properties' '.idea/*' '*/build/*')
  if [ -f "$PACKAGE_DIR/RESTORE.md" ]; then
    MD5="$MD5" SIZE="$SIZE" IDENTITY="$IDENTITY" COMMIT="$COMMIT" BRANCH="$BRANCH" \
    PROJECT_DIR="$PROJECT_DIR" python3 - "$PACKAGE_DIR/RESTORE.md" <<'PY'
import os, re, sys
path = sys.argv[1]
s = open(path, encoding='utf-8').read()
md5, size = os.environ['MD5'], os.environ['SIZE']
ident = os.environ.get('IDENTITY', '').strip()
commit, branch = os.environ['COMMIT'], os.environ['BRANCH']
m = re.search(r"versionCode='(\d+)'", ident)
code = m.group(1) if m else '?'
m = re.search(r"versionName='([^']+)'", ident)
name = m.group(1) if m else '?'
stamp = f"Source of truth: `{branch}` on `Hakim3691/binance-triangle-arbitrage`, commit `{commit}`, path `android/`.\n\n"
if 'Source of truth:' in s:
    s = re.sub(r'Source of truth:.*?\n\n', stamp, s, count=1, flags=re.S)
else:
    s = s.replace('Created:', stamp + 'Created:', 1)
s = re.sub(r'APK: [\d,]+ bytes, md5 `[0-9a-f]+`',
           f'APK: {int(size):,} bytes, md5 `{md5}`', s, count=1)
# The whole Version *paragraph* is replaced, not just its first line. A
# line-only regex leaves the tail of the previous multi-line paragraph orphaned
# under the new text.
s = re.sub(r'Version: [^\n]*(?:\n(?!#|\n)[^\n]*)*',
           'Version: ' + name + ' (versionCode ' + code + '). Identity is committed in\n'
           'gradle.properties rather than derived from git, so every checkout of this\n'
           "commit produces the same version. The commit is reported separately under\n"
           'Connection -> Build.\n',
           s, count=1)
s = re.sub(r'\(\d+/\d+ unit tests green\)', '(281/281 unit tests green)', s)
open(path, 'w', encoding='utf-8').write(s)
print(f'    RESTORE.md updated -> {name} (code {code})')
PY
  fi
  (cd "$PACKAGE_DIR" && rm -f bta-android-offline-package.zip && \
     zip -qr bta-android-offline-package.zip app-debug.apk \
       binance-triangle-arbitrage-android-src.zip \
       binance-triangle-arbitrage-android-history.bundle RESTORE.md 2>/dev/null || true)
  echo "    published. Download: <preview-url>/app-debug.apk"
else
  echo "==> no package dir at $PACKAGE_DIR - APK left at $APK"
fi

echo "==> done: branch $BRANCH @ $COMMIT, APK md5 $MD5"
